/*
 * This code was generated by the CGbR generator on 23.05.2016. Any manual changes will be lost on the next build.
 * 
 * For questions or bug reports please refer to https://github.com/Toxantron/CGbR or contact the distributor of the
 * 3rd party generator target.
 */
using CGbR.Lib;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CGbR.GeneratorTests
{
    /// <summary>
    /// Auto generated class by CGbR project
    /// </summary>
    public partial class ByteProperties : IByteSerializable
    {
        #region BinarySerializer

        /// <summary>
        /// Binary size of the object
        /// </summary>
        public int Size
        {
            get 
            { 
                var size = 3;
                // Add size for collections and strings
                size += Bytes == null ? 0 : Bytes.Length;
  
                return size;              
            }
        }

        /// <summary>
        /// Convert object to bytes
        /// </summary>
        public byte[] ToBytes()
        {
            var index = 0;
            var bytes = new byte[Size];

            return ToBytes(bytes, ref index);
        }

        /// <summary>
        /// Convert object to bytes within object tree
        /// </summary>
        void IByteSerializable.ToBytes(byte[] bytes, ref int index)
        {
            ToBytes(bytes, ref index);
        }

        /// <summary>
        /// Convert object to bytes within object tree
        /// </summary>
        public byte[] ToBytes(byte[] bytes, ref int index)
        {
            if (index + Size > bytes.Length)
                throw new ArgumentOutOfRangeException("index", "Object does not fit in array");

            // Convert SingleByte
            bytes[index++] = SingleByte;
            // Convert Bytes
            // Two bytes length information for each dimension
            GeneratorByteConverter.Include((ushort)(Bytes == null ? 0 : Bytes.Length), bytes, ref index);
            if (Bytes != null)
            {
            	Buffer.BlockCopy(Bytes, 0, bytes, index, Bytes.Length);
            	index += Bytes.Length;
            }
            return bytes;
        }

        /// <summary>
        /// Create object from byte array
        /// </summary>
        public ByteProperties FromBytes(byte[] bytes)
        {
            var index = 0;            
            return FromBytes(bytes, ref index); 
        }

        /// <summary>
        /// Create object from segment in byte array
        /// </summary>
        void IByteSerializable.FromBytes(byte[] bytes, ref int index)
        {
            FromBytes(bytes, ref index);
        }

        /// <summary>
        /// Create object from segment in byte array
        /// </summary>
        public ByteProperties FromBytes(byte[] bytes, ref int index)
        {
            // Read SingleByte
            SingleByte = bytes[index++];
            // Read Bytes
            var bytesLength = GeneratorByteConverter.ToUInt16(bytes, ref index);
            var tempBytes = new byte[bytesLength];
            for (var i = 0; i < bytesLength; i++)
            {
            	var value = bytes[index++];
                tempBytes[i] = value;
            }
            Bytes = tempBytes;

            return this;
        }

        
        #endregion

    }
}