// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CGbR
{
    using System.Linq;
    using System.Runtime.Serialization;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    internal partial class BinarySerializerGenerator : BinarySerializerGeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("        /// <summary>\r\n        /// Binary size of the object\r\n        /// </summa" +
                    "ry>\r\n        public int Size\r\n        {\r\n            get \r\n            { \r\n     " +
                    "           var size = ");
            
            #line 13 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BinarySize.OfClass(Model, Tools)));
            
            #line default
            #line hidden
            this.Write(";\r\n                // Add size for collections and strings\r\n");
            
            #line 15 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"

    foreach (var property in Model.Properties.Where(BinarySize.IsVariable)
                                             .Where(p => p.HasAttribute(nameof(DataMemberAttribute))))
    {
        string entrySize;
        switch (property.ValueType)
        {
			case ModelValueType.Class:
				// Find class from other messages
                entrySize = Tools.ReferenceSize(Model, property);
                if (entrySize == null)
                    continue;
				break;
			case ModelValueType.String:
                // Flexible strings are only included as their length because the length field is part of the fixed size
                entrySize = property.IsCollection ? "Sum(s => s.Length + 2)" : "Length";
                break;
            case ModelValueType.Byte:
                entrySize = "Length";
                break;
			default:
                entrySize = $"{GeneratorTools.CollectionSize(property)} * {BinarySize.OfProperty(property)}";
				break;
        }

            
            #line default
            #line hidden
            this.Write("                size += ");
            
            #line 40 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" == null ? 0 : ");
            
            #line 40 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture($"{property.Name}.{entrySize}"));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 41 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"

    }

            
            #line default
            #line hidden
            this.Write(@"  
                return size;              
            }
        }

        /// <summary>
        /// Convert object to bytes
        /// </summary>
        public byte[] ToBytes()
        {
            var index = 0;
            var bytes = new byte[Size];

            return ToBytes(bytes, ref index);
        }

        /// <summary>
        /// Convert object to bytes within object tree
        /// </summary>
        void IByteSerializable.ToBytes(byte[] bytes, ref int index)
        {
            ToBytes(bytes, ref index);
        }

        /// <summary>
        /// Convert object to bytes within object tree
        /// </summary>
        public byte[] ToBytes(byte[] bytes, ref int index)
        {
            if (index + Size > bytes.Length)
                throw new ArgumentOutOfRangeException(""index"", ""Object does not fit in array"");

");
            
            #line 75 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"

    foreach (var property in Model.Properties.WhereAttribute(nameof(DataMemberAttribute)))
    {

            
            #line default
            #line hidden
            this.Write("            // Convert ");
            
            #line 79 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 80 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"

        ToBytes(property);          
    }

            
            #line default
            #line hidden
            this.Write("            return bytes;\r\n        }\r\n\r\n        /// <summary>\r\n        /// Create" +
                    " object from byte array\r\n        /// </summary>\r\n        public ");
            
            #line 90 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(@" FromBytes(byte[] bytes)
        {
            var index = 0;            
            return FromBytes(bytes, ref index); 
        }

        /// <summary>
        /// Create object from segment in byte array
        /// </summary>
        void IByteSerializable.FromBytes(byte[] bytes, ref int index)
        {
            FromBytes(bytes, ref index);
        }

        /// <summary>
        /// Create object from segment in byte array
        /// </summary>
        public ");
            
            #line 107 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(" FromBytes(byte[] bytes, ref int index)\r\n        {\r\n");
            
            #line 109 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"

    foreach (var property in Model.Properties.WhereAttribute(nameof(DataMemberAttribute)))
    {

            
            #line default
            #line hidden
            this.Write("            // Read ");
            
            #line 113 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 114 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"

        FromBytes(property);
    }

            
            #line default
            #line hidden
            this.Write("\r\n            return this;\r\n        }\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 121 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"

    //---------------------------------------------
    // Generate a byte conversion for this field 
    //--------------------------------------------
    private void ToBytes(PropertyModel property)
    {
        // Indentation throughout the method
        var indent = property.IsCollection && property.ValueType != ModelValueType.Byte ? "\t" : string.Empty;

        // Optional length prefix
        GenerateLengthPrefix(property);

        CollectionWrapper(property, true);

        // Now we add the real value
        var target = property.IsCollection ? "value" : property.Name;
        var nullable = false;
        string conversion, increment = null;
        switch (property.ValueType)
        {
            case ModelValueType.String:
                conversion = $"GeneratorByteConverter.Include({target}, bytes, ref index)";
                break;
            case ModelValueType.Class:
                conversion = Tools.ClassToBytes(Model, property);
                break;
            case ModelValueType.Boolean:
                conversion = $"bytes[index++] = {target} ? (byte)1 : (byte)0";
                break;
            case ModelValueType.Byte:
                conversion = property.IsCollection ? BlockCopy(false, property.Name, $"{property.Name}.Length") : $"bytes[index++] = {target}";
                increment = property.IsCollection ? $"{property.Name}.Length" : null;
                nullable = property.IsCollection;
                break;
            default:
                conversion = BlockCopy(true, target, BinarySize.OfProperty(property).ToString("D"));
                break;
        }

        if (nullable || property.IsCollection)
        {
            indent += "\t";
        }

        NullableWrapper(property, nullable, true);


        
        #line default
        #line hidden
        
        #line 167 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write("            ");

        
        #line default
        #line hidden
        
        #line 168 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(indent));

        
        #line default
        #line hidden
        
        #line 168 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(conversion));

        
        #line default
        #line hidden
        
        #line 168 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 169 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"

        if (!string.IsNullOrEmpty(increment))
        {

        
        #line default
        #line hidden
        
        #line 172 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write("            ");

        
        #line default
        #line hidden
        
        #line 173 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(indent));

        
        #line default
        #line hidden
        
        #line 173 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write("index += ");

        
        #line default
        #line hidden
        
        #line 173 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(increment));

        
        #line default
        #line hidden
        
        #line 173 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 174 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"

        }

        NullableWrapper(property, nullable, false);

        CollectionWrapper(property, false);
    }

    //-------------------------------------------------------
    // Generate 2 byte length prefix for collection length 
    //-------------------------------------------------------
    private void GenerateLengthPrefix(PropertyModel property)
    {
        if (!property.IsCollection)
            return;
        

        
        #line default
        #line hidden
        
        #line 190 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write("            // Two bytes length information for each dimension\r\n");

        
        #line default
        #line hidden
        
        #line 192 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"

        for (var dimension = 0; dimension < property.Dimensions; dimension++)
        {

        
        #line default
        #line hidden
        
        #line 195 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write("            ");

        
        #line default
        #line hidden
        
        #line 196 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(BlockCopy(true, $"(ushort)({property.Name} == null ? 0 : {property.Name}.{GeneratorTools.CollectionSize(property, property.Dimensions > 1 ? dimension : -1 )})", "2")));

        
        #line default
        #line hidden
        
        #line 196 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 197 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
   
        }  
    }

    //--------------------------------------
    // Generate the Buffer.BlockCopy code
    //--------------------------------------
    private static string BlockCopy(bool bitConverter, string source, string length)
    {
        return bitConverter 
            ? $"GeneratorByteConverter.Include({source}, bytes, ref index)"
            : $"Buffer.BlockCopy({source}, 0, bytes, index, {length})";
    }

    //--------------------------------------
    // Wrap conversion of nullable property
    //--------------------------------------
    private void NullableWrapper(PropertyModel property,bool nullable, bool header)
    {
        if (!nullable)
            return;

        if (header)
        {

        
        #line default
        #line hidden
        
        #line 221 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write("            if (");

        
        #line default
        #line hidden
        
        #line 222 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));

        
        #line default
        #line hidden
        
        #line 222 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(" != null)\r\n            {\r\n");

        
        #line default
        #line hidden
        
        #line 224 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"

        }
        else
        {

        
        #line default
        #line hidden
        
        #line 228 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write("            }\r\n");

        
        #line default
        #line hidden
        
        #line 230 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"

        }
    }

    //--------------------------------------
    // Code fragments wrapping a collection
    //--------------------------------------
    private void CollectionWrapper(PropertyModel property, bool start)
    {
        if (!property.IsCollection || property.ValueType == ModelValueType.Byte)
            return;

        if (start)
        {

        
        #line default
        #line hidden
        
        #line 244 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write("            if (");

        
        #line default
        #line hidden
        
        #line 245 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));

        
        #line default
        #line hidden
        
        #line 245 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(" != null)\r\n            {\r\n");

        
        #line default
        #line hidden
        
        #line 247 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"

            if (GeneratorTools.SupportsForLoop(property))
            {
                var dimensions = new[] { "i", "j", "k" };
                for (var dimension = 0; dimension < property.Dimensions; dimension++)
                {
                    var targetDimension = property.Dimensions > 1 ? dimension : -1;


        
        #line default
        #line hidden
        
        #line 255 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write("                for(var ");

        
        #line default
        #line hidden
        
        #line 256 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dimensions[dimension]));

        
        #line default
        #line hidden
        
        #line 256 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(" = 0; ");

        
        #line default
        #line hidden
        
        #line 256 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dimensions[dimension]));

        
        #line default
        #line hidden
        
        #line 256 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(" < ");

        
        #line default
        #line hidden
        
        #line 256 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));

        
        #line default
        #line hidden
        
        #line 256 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 256 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GeneratorTools.CollectionSize(property, targetDimension)));

        
        #line default
        #line hidden
        
        #line 256 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write("; ");

        
        #line default
        #line hidden
        
        #line 256 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dimensions[dimension]));

        
        #line default
        #line hidden
        
        #line 256 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write("++)\r\n");

        
        #line default
        #line hidden
        
        #line 257 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"

                }

        
        #line default
        #line hidden
        
        #line 259 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write("                {\r\n                    var value = ");

        
        #line default
        #line hidden
        
        #line 261 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));

        
        #line default
        #line hidden
        
        #line 261 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write("[");

        
        #line default
        #line hidden
        
        #line 261 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(",", Enumerable.Range(0, property.Dimensions).Select(i => dimensions[i]))));

        
        #line default
        #line hidden
        
        #line 261 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write("];\r\n");

        
        #line default
        #line hidden
        
        #line 262 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"

            }
            else
            {

        
        #line default
        #line hidden
        
        #line 266 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write("                foreach(var value in ");

        
        #line default
        #line hidden
        
        #line 267 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));

        
        #line default
        #line hidden
        
        #line 267 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(")\r\n                {\r\n");

        
        #line default
        #line hidden
        
        #line 269 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"


            }
        }
        else
        {

        
        #line default
        #line hidden
        
        #line 275 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write("                }\r\n            }\r\n");

        
        #line default
        #line hidden
        
        #line 278 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"

        }
    }

    //--------------------------------------
    // Read property from the byte stream
    //--------------------------------------
    private void FromBytes(PropertyModel property)
    {
        var target = property.IsCollection ? "var value" : property.Name;
	    var indent = property.IsCollection ? "\t" : string.Empty;

	    var increment = string.Empty;
	    string conversion;
	    switch (property.ValueType)
	    {
	        case ModelValueType.Class:
	            conversion = Tools.ClassFromBytes(Model, property);
	            break;
	        case ModelValueType.Byte:
	            conversion = "bytes[index++]";
	            break;
		    case ModelValueType.String:
	            conversion = $"GeneratorByteConverter.GetString(bytes, ref index)";
			    break;
	        default:
			    conversion = $"GeneratorByteConverter.To{property.ValueType.ToString("G")}(bytes, ref index)";
	            break;
	    }

        GenerateReadLoop(property, true);


        
        #line default
        #line hidden
        
        #line 310 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write("            ");

        
        #line default
        #line hidden
        
        #line 311 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(indent));

        
        #line default
        #line hidden
        
        #line 311 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(target));

        
        #line default
        #line hidden
        
        #line 311 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(" = ");

        
        #line default
        #line hidden
        
        #line 311 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(conversion));

        
        #line default
        #line hidden
        
        #line 311 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 312 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"

        if (!string.IsNullOrEmpty(increment))
        {

        
        #line default
        #line hidden
        
        #line 315 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write("            ");

        
        #line default
        #line hidden
        
        #line 316 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(indent));

        
        #line default
        #line hidden
        
        #line 316 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write("index += ");

        
        #line default
        #line hidden
        
        #line 316 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(increment));

        
        #line default
        #line hidden
        
        #line 316 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 317 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"

        }

        GenerateReadLoop(property, false);
        
    }

    //----------------------------------------
    // Generate loop for reading collections
    //----------------------------------------
    private void GenerateReadLoop(PropertyModel property, bool header)
    {
        if (!property.IsCollection) 
            return;

        if (header)
        {
            // Read the length
            for (var dimension = 0; dimension < property.Dimensions; dimension++)
            {

        
        #line default
        #line hidden
        
        #line 337 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write("            var ");

        
        #line default
        #line hidden
        
        #line 338 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(FieldLength(property, dimension)));

        
        #line default
        #line hidden
        
        #line 338 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(" = GeneratorByteConverter.ToUInt16(bytes, ref index);\r\n");

        
        #line default
        #line hidden
        
        #line 339 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"

            }
        }

        if(header && property.IsCollection)
        {
            // Create temp object

        
        #line default
        #line hidden
        
        #line 346 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write("            var temp");

        
        #line default
        #line hidden
        
        #line 347 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));

        
        #line default
        #line hidden
        
        #line 347 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(" = ");

        
        #line default
        #line hidden
        
        #line 347 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(GeneratorTools.CollectionConstructor(property, FieldLength(property))));

        
        #line default
        #line hidden
        
        #line 347 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 348 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
 
             
            // Generate the loop
            var dimensions = new[] { "i", "j", "k" };
            for (var dimension = 0; dimension < property.Dimensions; dimension++)
            {

        
        #line default
        #line hidden
        
        #line 354 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write("            for (var ");

        
        #line default
        #line hidden
        
        #line 355 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dimensions[dimension]));

        
        #line default
        #line hidden
        
        #line 355 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(" = 0; ");

        
        #line default
        #line hidden
        
        #line 355 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dimensions[dimension]));

        
        #line default
        #line hidden
        
        #line 355 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(" < ");

        
        #line default
        #line hidden
        
        #line 355 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(FieldLength(property, dimension)));

        
        #line default
        #line hidden
        
        #line 355 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write("; ");

        
        #line default
        #line hidden
        
        #line 355 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dimensions[dimension]));

        
        #line default
        #line hidden
        
        #line 355 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write("++)\r\n");

        
        #line default
        #line hidden
        
        #line 356 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"

            }

        
        #line default
        #line hidden
        
        #line 358 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write("            {\r\n");

        
        #line default
        #line hidden
        
        #line 360 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
           
        }
        else if(!header && property.IsCollection)
        {
            var collAssignment = property.CollectionType == "Array"
                ? $"temp{property.Name}[{FieldPosition(property)}] = value" 
                : $"temp{property.Name}.Add(value)";


        
        #line default
        #line hidden
        
        #line 368 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write("                ");

        
        #line default
        #line hidden
        
        #line 369 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(collAssignment));

        
        #line default
        #line hidden
        
        #line 369 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(";\r\n            }\r\n            ");

        
        #line default
        #line hidden
        
        #line 371 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));

        
        #line default
        #line hidden
        
        #line 371 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(" = temp");

        
        #line default
        #line hidden
        
        #line 371 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));

        
        #line default
        #line hidden
        
        #line 371 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 372 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"
   
        }
    }

    //---------------------------
    // Generate length variable
    //---------------------------
    private static string FieldLength(PropertyModel property)
    {
        return string.Join(",", Enumerable.Range(0, property.Dimensions).Select(i => FieldLength(property, i)));
    }

    //---------------------------
    // Generate length variable
    //---------------------------
    private static string FieldPosition(PropertyModel property)
    {
        var dimensions = new[] { "i", "j", "k" };
        return string.Join(",", Enumerable.Range(0, property.Dimensions).Select(i => dimensions[i]));
    }

    //---------------------------
    // Generate length variable
    //---------------------------
    private static string FieldLength(CodeElementModel property, int dimension)
    {
        var dimensions = new[] {"Length", "Width", "Height"};
        return property.Name.ToLower() + dimensions[dimension];
    }

        
        #line default
        #line hidden
        
        #line 1 "C:\Users\Thomas\Documents\Development\CGbR\CGbR\Generator\Serialization\BinarySerializerGenerator.tt"

private global::CGbR.ClassModel _ModelField;

/// <summary>
/// Access the Model parameter of the template.
/// </summary>
private global::CGbR.ClassModel Model
{
    get
    {
        return this._ModelField;
    }
}

private global::CGbR.IClassSerializationTools _ToolsField;

/// <summary>
/// Access the Tools parameter of the template.
/// </summary>
private global::CGbR.IClassSerializationTools Tools
{
    get
    {
        return this._ToolsField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool ModelValueAcquired = false;
if (this.Session.ContainsKey("Model"))
{
    this._ModelField = ((global::CGbR.ClassModel)(this.Session["Model"]));
    ModelValueAcquired = true;
}
if ((ModelValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Model");
    if ((data != null))
    {
        this._ModelField = ((global::CGbR.ClassModel)(data));
    }
}
bool ToolsValueAcquired = false;
if (this.Session.ContainsKey("Tools"))
{
    this._ToolsField = ((global::CGbR.IClassSerializationTools)(this.Session["Tools"]));
    ToolsValueAcquired = true;
}
if ((ToolsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Tools");
    if ((data != null))
    {
        this._ToolsField = ((global::CGbR.IClassSerializationTools)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    internal class BinarySerializerGeneratorBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
